# description: Dictionaries for HBV and human splice sites.

ssdict = {"GT(hg19_donor)": "GU (hs donor)",
        "AG(hg19_acceptor)": "AG (hs acceptor)",
        "GT(hg19_non-donor)": "GU (hs non-donor)",
        "AG(hg19_non-acceptor)": "AG (hs non-acceptor)",
        "GT(A2_donor)": "GU (HBV donor)",
        "AG(A2_acceptor)": "AG (HBV acceptor)",
        "GT(A2_non-donor)": "GU (HBV non-donor)",
        "AG(A2_non-acceptor)": "AG (HBV non-acceptor)",
        "GT(B2_donor)": "GU (HBV donor)",
        "AG(B2_acceptor)": "AG (HBV acceptor)",
        "GT(B2_non-donor)": "GU (HBV non-donor)",
        "AG(B2_non-acceptor)": "AG (HBV non-acceptor)",
        "GT(C2_donor)": "GU (HBV donor)",
        "AG(C2_acceptor)": "AG (HBV acceptor)",
        "GT(C2_non-donor)": "GU (HBV non-donor)",
        "AG(C2_non-acceptor)": "AG (HBV non-acceptor)",
        "GT(D3_donor)": "GU (HBV donor)",
        "AG(D3_acceptor)": "AG (HBV acceptor)",
        "GT(D3_non-donor)": "GU (HBV non-donor)",
        "AG(D3_non-acceptor)": "AG (HBV non-acceptor)"}

sslab = {"GT(hg19_donor)": "GU (donor)",
        "AG(hg19_acceptor)": "AG (acceptor)",
        "GT(hg19_non-donor)": "GU (non-donor)",
        "AG(hg19_non-acceptor)": "AG (non-acceptor)",
        "GT(A2_donor)": "GU (donor)",
        "AG(A2_acceptor)": "AG (acceptor)",
        "GT(A2_non-donor)": "GU (non-donor)",
        "AG(A2_non-acceptor)": "AG (non-acceptor)",
        "GT(B2_donor)": "GU (donor)",
        "AG(B2_acceptor)": "AG (acceptor)",
        "GT(B2_non-donor)": "GU (non-donor)",
        "AG(B2_non-acceptor)": "AG (non-acceptor)",
        "GT(C2_donor)": "GU (donor)",
        "AG(C2_acceptor)": "AG (acceptor)",
        "GT(C2_non-donor)": "GU (non-donor)",
        "AG(C2_non-acceptor)": "AG (non-acceptor)",
        "GT(D3_donor)": "GU (donor)",
        "AG(D3_acceptor)": "AG (acceptor)",
        "GT(D3_non-donor)": "GU (non-donor)",
        "AG(D3_non-acceptor)": "AG (non-acceptor)"}

ssize = {"GT(hg19_donor)": 10,
        "AG(hg19_acceptor)": 10,
        "GT(hg19_non-donor)": 10,
        "AG(hg19_non-acceptor)": 10,
        "GT(A2_donor)": 100,
        "AG(A2_acceptor)": 100,
        "GT(A2_non-donor)": 10,
        "AG(A2_non-acceptor)": 10,
        "GT(B2_donor)": 100,
        "AG(B2_acceptor)": 100,
        "GT(B2_non-donor)": 10,
        "AG(B2_non-acceptor)": 10,
        "GT(C2_donor)": 100,
        "AG(C2_acceptor)": 100,
        "GT(C2_non-donor)": 10,
        "AG(C2_non-acceptor)": 10,
        "GT(D3_donor)": 100,
        "AG(D3_acceptor)": 100,
        "GT(D3_non-donor)": 10,
        "AG(D3_non-acceptor)": 10}